server:
  port: 8080

spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/pricedb
    url: jdbc:postgresql://etake-db.postgres.database.azure.com:5432/etakeDB?sslmode=require
    username: etakeAdmin@etake-db
    password: Alonso1236542!
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  main:
    allow-circular-references: true
  mvc:
    throw-exception-if-no-handler-found: true
  sql:
    init:
      mode: always