runtime: java11
instance_class: F2
entrypoint: java -noverify -jar prices-0.0.1-SNAPSHOT.jar
#env: flex
#runtime_config:
#  jdk: openjdk11
#handlers:
#  -url: /prices
#  script: this field is required, but ignored
#resources:
#  cpu: 1
#  memory_gb: 2.3
#  disk_size_gb: 10
#  volumes:
#    - name: autoorder-batch
#      volume_type: tmpfs
#      size_gb: 0.5
